
services:
  postgres_alfaeduca:
    container_name: postgres_alfaeducadb
    image: postgres
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=pg_alfaeduca
    volumes:
      - postgres_data:/var/lib/postgresql/data

  alfaeduca_app:
    container_name: alfaeduca_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - postgres_alfaeduca

volumes:
  postgres_data:
