
services:
  postgres_alfaeduca:
    container_name: postgres_alfaeducadb
    image: postgres
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=pg_alfaeduca
    volumes:
      - postgres_data:/var/lib/postgresql/data
  alfaeduca_app:
    container_name: alfaeduca_app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MAVEN_OPTS: "-Dmaven.repo.local=/root/.m2/repository"
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - CORS_ORIGIN=http://localhost:3000
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_EMAILS=${ADMIN_EMAILS}
    ports:
      - "8081:8081"
    depends_on:
      - postgres_alfaeduca

volumes:
  postgres_data:
