
services:
  postgres_alfaeduca:
    container_name: postgres_alfaeducadb
    image: postgres
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=pg_alfaeduca
    volumes:
      - postgres_data:/var/lib/postgresql/data

  alfaeduca_app:
    container_name: alfaeduca_app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MAVEN_OPTS: "-Dmaven.repo.local=/root/.m2/repository"
    ports:
      - "8081:8081"
    depends_on:
      - postgres_alfaeduca
      - ollama_service
    environment:
      - OLLAMA_HOST=http://ollama_service:11434

  ollama_service:
    container_name: ollama_llm
    build:
      context: .
      dockerfile: Dockerfile.ollama
    ports:
      - "11434:11434"
    environment:
      # ID do arquivo no Google Drive (extrair da URL de compartilhamento)
      - GDRIVE_FILE_ID=${GDRIVE_FILE_ID}
      # Nome do arquivo do modelo
      - MODEL_NAME=${MODEL_NAME}
      # Modelo padrão para baixar do repositório Ollama (opcional)
      - DEFAULT_MODEL=${DEFAULT_MODEL}
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

volumes:
  postgres_data:
  ollama_data:
