ALTER TABLE usuarios
ALTER COLUMN nivel DROP NOT NULL,
ALTER COLUMN pontos DROP NOT NULL;

UPDATE usuarios SET nivel = 0, pontos = 0 WHERE nivel IS NULL OR pontos IS NULL;

ALTER TABLE usuarios
ALTER COLUMN nivel SET DEFAULT 0,
ALTER COLUMN pontos SET DEFAULT 0;